SEVER_NAME = 'bnaibS'
SERVER_IP = '192.168.42.110'

VB_CPU = 3
VB_RAM = 8192

M_VM = 'virtualbox'

VM_BOX = "bento/centos-8"
# VM_BOX_URL = "https://app.vagrantup.com/bento/boxes/centos-8/versions/202112.19.0/providers/virtualbox.box"
# VM_BOX_URL = "file:////Users/bnaib/goinfre/Images/centos8.virtualbox"
VM_BOX_URL = "file://~/goinfre/Images/centos8.virtualbox"
VM_BOX_CHECK_UPDATE = false

Vagrant.configure("2") do |config|
    config.vm.box = VM_BOX
    config.vm.box_url = VM_BOX_URL
    config.vm.box_check_update = VM_BOX_CHECK_UPDATE

    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    config.vm.network "forwarded_port", guest: 8082, host: 8082

    config.vm.define SEVER_NAME do |control|
        control.vm.hostname = SEVER_NAME
        control.vm.network :private_network, ip: SERVER_IP
        # control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--name", SEVER_NAME]
            vb.memory = VB_RAM
            vb.cpus = VB_CPU
            # --natdnshostresolver<1-N> on|off - Makes the NAT engine use the host's resolver mechanisms to handle DNS requests
            # Настройка virtualbox
            # Заставляет механизм NAT использовать механизмы преобразователя хоста для обработки DNS-запросов
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            # --natdnsproxy<1-N> on|off: Makes the NAT engine proxy all guest DNS requests to the host's DNS servers
            # Настройка virtualbox
            # Делает механизм NAT прокси-сервером для всех гостевых DNS-запросов к DNS-серверам хоста.
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end

        control.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"

        control.vm.provision "shell", privileged: true, path: "./keys.sh"

        # control.vm.synced_folder ".", "/vagrant"

        # # Копируем ключ для доступа по SSH
        # control.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"

        # # Копируем ключ для доступа к серверу
        # control.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"

        # control.vm.provision "file", source: "./cfg/app1.yml", destination: "/tmp/app1.yml"
        # control.vm.provision "file", source: "./cfg/app2.yml", destination: "/tmp/app2.yml"
        # control.vm.provision "file", source: "./cfg/app3.yml", destination: "/tmp/app3.yml"
        # control.vm.provision "file", source: "./cfg/ing0.yml", destination: "/tmp/ing0.yml"

        # control.vm.provision "file", source: "./scripts/config/argo.yml", destination: "/vagrant/scripts/config/ing0.yml"

        # # privileged: true - команды будет выполняться из под sudo
        # control.vm.provision "shell", privileged: false, path: "scripts/server.sh"
    end
end
