apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.56.20:8081/bnaib/bnaib_iot_app_config.git
    targetRevision: HEAD
    path: p3/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
